Added new servlet for create new event page
kassidywebb/codeu-team2-sp19 pull request #32
Opened 2019-03-23 00:00 UTC by imanityson

Right now the servlet is very basic, it just asks the user to input information for each category. I need to pull event.java to figure out how to store the information there but I hope to get the rest of the servlet done by tomorrow.

2019-03-23 07:41 UTC, Ajide49 reviewed
I believe we will need to implement Blobstore like in the MessageServlet.java for this new servlet

2019-03-27 22:23 UTC, kassidywebb requested changes

2019-03-27 22:23 UTC, kassidywebb commented on target/codeu-starter-project-0.0.1-SNAPSHOT/js/user-page-loader.js
> +  bodyDiv.innerHTML = handleBBCode(message.text);
so are we doing BBCode now? Because I thought we didn't need it?

2019-03-27 22:23 UTC, kassidywebb commented on target/codeu-starter-project-0.0.1-SNAPSHOT/js/user-page-loader.js
> +
is this space necessary?

2019-03-29 14:12 UTC, ryanluo requested changes
Why are the binary class files included? Shouldn't they be ignored?

2019-03-29 14:12 UTC, ryanluo commented on src/main/java/com/google/codeu/servlets/CreateNewEventServlet.java
> +
nit:remove line

2019-03-29 14:12 UTC, ryanluo commented on src/main/java/com/google/codeu/servlets/CreateNewEventServlet.java
> +
Shouldn't you be setting the response to something?

2019-03-30 02:53 UTC, ryanluo commented
Imani, were these comments addressed?

2019-03-31 22:13 UTC, closed without merging