Add new servlet to get Individual Event, Add a empty constructor in the ...
kassidywebb/codeu-team2-sp19 pull request #38
Opened 2019-03-30 22:15 UTC by vado21

class event and add two functions in Datastore to request the Event.

2019-03-31 02:12 UTC, Ajide49 commented on src/main/java/com/google/codeu/data/Datastore.java
> +  /**This function returns one Event given a query**/
The description of the function seems incorrect, I would change this as an event is not being returned in saveIndividualEvent.

2019-03-31 02:15 UTC, Ajide49 commented
Great job with the pull request Eduardo! I don't have any real complaints other than you'll need to change how the event objects are being saved, because of my pull request. Timestamp and time should both be included. You had good spacing, nice flow in logic, and overall did a good job.

2019-03-31 20:48 UTC, kassidywebb requested changes

2019-03-31 20:48 UTC, kassidywebb commented on src/main/java/com/google/codeu/data/Event.java
> +  public Event(){
Is all of this necessary? This doesn't have this in the Message.java file, so could you explain why it is?

2019-04-01 14:19 UTC, ryanluo requested changes

2019-04-01 14:19 UTC, ryanluo commented on src/main/java/com/google/codeu/data/Datastore.java
> +  public void saveIndividualEvent(Event event,PreparedQuery results) {
nit: Use 2 spaces instead of tab for indentation for consistency.

2019-04-01 14:19 UTC, ryanluo commented on src/main/java/com/google/codeu/data/Datastore.java
> +			float sentimentScore = entity.getProperty("sentimentScore") == null? (float) 0.0 : ((Double) entity.getProperty("sentimentScore")).floatValue();
@kassidywebb Aren't we removing sentiment?

2019-04-01 14:19 UTC, ryanluo commented on src/main/java/com/google/codeu/data/Datastore.java
> +		} catch (Exception e) {
What exactly are you catching here? What could go wrong?

2019-04-01 14:19 UTC, ryanluo commented on src/main/java/com/google/codeu/data/Datastore.java
> +	for (Entity entity : results.asIterable()) {
Why are there multiple results? Shouldn't there just be one entity that your'e saving?

2019-04-02 15:20 UTC, kassidywebb approved these changes

2019-04-02 23:36 UTC, merged